- hosts: all
  gather_facts: false
  become: true
  tasks:
    - import_tasks: dependencies.yml

    - name: Init a new swarm with default parameters
      docker_swarm:
        state: present
        advertise_addr: 192.168.56.20

    - name: Get info on Docker Swarm
      docker_swarm_info:
      ignore_errors: yes
      register: result

    - name: Inform about basic flags
      debug:
        msg: |
          Was able to talk to docker daemon: {{ result.can_talk_to_docker }}
          Docker in Swarm mode: {{ result.docker_swarm_active }}
          This is a Manager node: {{ result.docker_swarm_manager }}


    - name: Get info on Docker Swarm and list of registered nodes
      docker_swarm_info:
        nodes: yes
      register: result
     
    - debug:
        var: result.swarm_facts

