Vagrant.configure(2) do |config|

  config.vm.define "docker1" do |docker1|
    docker1.vm.box = "rodrigodlima/mycentos7"
    docker1.vm.network "private_network", ip: "192.168.56.90"
    docker1.vm.hostname = "docker1"
  end

 config.vm.provision "shell", inline: <<-SHELL
  sudo curl -fsSL https://get.docker.com |bash
  sudo systemctl start docker
  sudo systemctl enable docker
 SHELL
end
