Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  vm.box = "rodrigodlima/mycentos7"
 
  config.vm.define "mongodb01" do |mongodb01|
    mongodb01.vm.network "private_network", ip: "192.168.56.90"
    mongodb01.vm.hostname = "mongodb0101"
 
    mongodb01.vm.provider "virtualbox" do |v|
      v.name = "mongodb01"
      v.memory = 2048
      v.cpus =2
    end 
  end

  config.vm.define "mongodb02" do |mongodb02|
    mongodb02.vm.network "private_network", ip: "192.168.56.91"
    mongodb02.vm.hostname = "mongodb02"

    mongodb02.vm.provider "virtualbox" do |v|
      v.name = "mongodb02"
      v.memory = 2048
      v.cpus =2
    end
  end

  config.vm.define "mongodb03" do |mongodb03|
    mongodb03.vm.network "private_network", ip: "192.168.56.91"
    mongodb03.vm.hostname = "mongodb03"

    mongodb03.vm.provider "virtualbox" do |v|
      v.name = "mongodb03"
      v.memory = 2048
      v.cpus =2
    end
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "site.yml"
    ansible.inventory_path = "inventories/local/hosts"
  end
end
