Vagrant.configure(2) do |config|

  config.vm.define "mongodb" do |mongodb|
    mongodb.vm.box = "rodrigodlima/mycentos7"
    mongodb.vm.network "private_network", ip: "192.168.56.90"
    mongodb.vm.hostname = "mongodb"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install git ansible ca-certificates -y
    sudo cp /vagrant/*.crt /etc/pki/ca-trust/source/anchors/
    sudo update-ca-trust extract
    sudo git clone https://github.com/rodrigodlima/ansible-playbooks.git /tmp/ansible-playbooks/
    cd /tmp/ansible-playbooks && sudo ansible-playbook -i inventories/local/hosts playbook_mongo.yml
  SHELL


end
