- hosts: all
  gather_facts: true
  become: true
  #vars:
  #  hostname: '{{ ansible_facts['nodename'] }}'
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release

    - name: Install NGINX
      yum:
        name: nginx
    
    - name: Copy configuration file to LB
      copy:
        src: files/nginx-lb.conf
        dest: /etc/nginx/nginx.conf
      when: ansible_hostname == "nginxlb"
    
    - name: Copy index to respective server
      copy:
        src: files/index-v1.html
        dest: /usr/share/nginx/html/index.html
      when: ansible_hostname == "web-1"
    
    - name: Copy index to respective server
      copy:
        src: files/index-v2.html
        dest: /usr/share/nginx/html/index.html
      when: ansible_hostname == "web-2"
    
    - name: Start Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes