# -*- mode: ruby -*-
# vi: set ft=ruby :

loadbalancer_ip = "192.168.56.150"

Vagrant.configure("2") do |config|
  config.vm.define "nginxlb" do |nginxlb|
    nginxlb.vm.hostname = "nginxlb"
    nginxlb.vm.box = "centos/7"
    nginxlb.vm.network "private_network", ip: loadbalancer_ip

    nginxlb.vm.provider :virtualbox do |v|
      v.cpus = 2
      v.memory = 1024
    end


    nginxlb.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "nginx.yml"
      ansible.extra_vars = {
        node_ip: loadbalancer_ip,
      }
    end


  end

  (1..2).each do |i|
    config.vm.define "web-#{i}" do |web|
      web.vm.hostname = "web-#{i}"
      web.vm.box = "centos/7"
      web.vm.network "private_network", ip: "192.168.56.5#{i+2}"

      web.vm.provider :virtualbox do |v|
        v.cpus = 2
        v.memory = 1024
      end

      web.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "nginx.yml"
      end
    end
  end
end
