Vagrant.configure(2) do |config|

  config.vm.define "awx" do |awx|
    awx.vm.box = "rodrigodlima/mycentos7"
    awx.vm.network "private_network", ip: "192.168.56.20"
    awx.vm.hostname = "awx"
  end
 
 
 config.vm.provider "virtualbox" do |vb|
     vb.memory = "2000"
     vb.cpus = "2"
  end

 config.vm.provision "shell", inline: <<-SHELL
  sudo curl -fsSL https://get.docker.com |bash
  sudo systemctl start docker
  sudo systemctl enable docker
 SHELL
end
