$script = <<SCRIPT
rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh http://yum.spacewalkproject.org/2.7/RHEL/7/x86_64/spacewalk-repo-2.7-2.el7.noarch.rpm
cd /etc/yum.repos.d && curl -O https://copr.fedorainfracloud.org/coprs/g/spacewalkproject/java-packages/repo/epel-7/group_spacewalkproject-java-packages-epel-7.repo
yum update -y
yum install vim -y
yum install spacewalk-setup-postgresql -y
yum install spacewalk-postgresql -y



cat >> /etc/yum.repos.d/jpackage-generic.repo <<EOF
[jpackage-generic]
name=JPackage generic
baseurl=http://mirrors.dotsrc.org/pub/jpackage/5.0/generic/free/
mirrorlist=http://www.jpackage.org/mirrorlist.php?dist=generic&type=free&release=5.0
enabled=0
gpgcheck=1
gpgkey=http://www.jpackage.org/jpackage.asc
EOF

cat > /root/spacewalk_answers.txt << EOF
admin-email = your_email@domain.com
ssl-set-org = Spacewalk Org
ssl-set-org-unit = spacewalk
ssl-set-city = My City
ssl-set-state = My State
ssl-set-country = US
ssl-password = spacewalk
ssl-set-email = your_email@domain.com
ssl-config-sslvhost = Y
db-backend=postgresql
db-name=spacewalk
db-user=spacewalkuser
db-password=spacewalkpw
db-host=localhost
db-port=5432
enable-tftp=Y
EOF

spacewalk-setup --answer-file=/root/spacewalk_answers.txt

SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.network "public_network"
  config.vm.synced_folder "../data/spacewalk", "/srv/"
  config.vm.hostname = "spacewalk"
  config.vm.provision "shell", inline: $script
  config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
      vb.memory = "3000"
  end
end
