Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.85"
  config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get install python -y
  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end
end
