- hosts: all
  gather_facts: true
  become: true
  tasks:
    - import_tasks: k8s.yml

    - name: Kubernetes images pull
      shell: "kubeadm config images pull"
     
    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted
    
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address={{ node_ip }} --apiserver-cert-extra-sans={{ node_ip }}  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
    
    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown -R vagrant:vagrant /home/vagrant/.kube
       
    - name: Install wavenet
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
      become: false

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"