Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.provider "virtualbox" do |katello|
     # Display the VirtualBox GUI when booting the machine
     katello.gui = true
  
  #   # Customize the amount of memory on the VM:
     katello.memory = "8192"
  end
end
